
-------------------------------XTablas ( Eliminar las tablas de la base de datos musician )-------------------------------


DROP TABLE band CASCADE CONSTRAINTS;
DROP TABLE composer CASCADE CONSTRAINTS;
DROP TABLE composition CASCADE CONSTRAINTS;
DROP TABLE concert CASCADE CONSTRAINTS;
DROP TABLE has_composed CASCADE CONSTRAINTS;
DROP TABLE musician CASCADE CONSTRAINTS;
DROP TABLE performance_  CASCADE CONSTRAINTS;
DROP TABLE performer CASCADE CONSTRAINTS;
DROP TABLE place CASCADE  CONSTRAINTS;
DROP TABLE plays_in CASCADE CONSTRAINTS;

-------------------------------XTablas ( Eliminar las tablas de la base de datos ride )-------------------------------
DROP TABLE Puntos CASCADE CONSTRAINTS ;
DROP TABLE Segmentos CASCADE CONSTRAINTS ;
DROP TABLE Registros CASCADE CONSTRAINTS ;

DROP TABLE Carreras CASCADE CONSTRAINTS;
DROP TABLE PropiedadDe CASCADE CONSTRAINTS;

DROP TABLE Miembros CASCADE CONSTRAINTS;
DROP TABLE Personas CASCADE CONSTRAINTS;
DROP TABLE Empresas CASCADE CONSTRAINTS;
DROP TABLE Ciclistas CASCADE CONSTRAINTS;

DROP TABLE Versiones CASCADE CONSTRAINTS;
DROP TABLE Participa CASCADE CONSTRAINTS;
DROP TABLE EsOrganizador CASCADE CONSTRAINTS;

--