/*XTablas*/

DROP TABLE Carreras CASCADE CONSTRAINTS;
DROP TABLE PropiedadDe CASCADE CONSTRAINTS;
DROP TABLE Puntos CASCADE CONSTRAINTS ;

DROP TABLE Segmentos CASCADE CONSTRAINTS ;
DROP TABLE Versiones CASCADE CONSTRAINTS;

DROP TABLE Registros CASCADE CONSTRAINTS ;
DROP TABLE Fotos CASCADE CONSTRAINTS;

DROP TABLE Miembros CASCADE CONSTRAINTS;
DROP TABLE Personas CASCADE CONSTRAINTS;
DROP TABLE Empresas CASCADE CONSTRAINTS;
DROP TABLE Ciclistas CASCADE CONSTRAINTS;


DROP TABLE Participa CASCADE CONSTRAINTS;
DROP TABLE EsOrganizador CASCADE CONSTRAINTS;

