DROP TABLE Patrocinadores 
CASCADE CONSTRAINTS  ;

DROP TABLE fechaPatrocinio 
CASCADE CONSTRAINTS  ;

DROP TABLE Eventos 
CASCADE CONSTRAINTS  ;

DROP TABLE Boletas 
CASCADE CONSTRAINTS  ;

DROP TABLE Zonas 
CASCADE CONSTRAINTS  ;

DROP TABLE Conciertos 
CASCADE CONSTRAINTS  ;

DROP TABLE esAsignado 
CASCADE CONSTRAINTS  ;

DROP TABLE Tiene 
CASCADE CONSTRAINTS  ;

DROP TABLE Camerinos 
CASCADE CONSTRAINTS  ;

DROP TABLE seAbasteceCon 
CASCADE CONSTRAINTS  ;

DROP TABLE Productos 
CASCADE CONSTRAINTS  ;

DROP TABLE Artistas 
CASCADE CONSTRAINTS  ;
