/*CRUDOK*/

/*PC_Proveedores*/
--ADICIONAR PROVEEDORES.
EXECUTE PC_Proveedores.AD_Proveedores(7543913, 9136885308, 'CC', 3618312530);
EXECUTE PC_Proveedores.AD_Proveedores(7783953, 8321526323, 'NT', 3992838251);
EXECUTE PC_Proveedores.AD_Proveedores(5855852, 5975542860, 'CC', 3942670281);
EXECUTE PC_Proveedores.AD_Proveedores(5555555, 5975554450, 'CC', 3542670281);

--ADICIONAR PERSONAS NATURALES.
EXECUTE PC_Proveedores.AD_PersonasNaturales(5855852, 'Camilo Rincon',   NULL);
EXECUTE PC_Proveedores.AD_PersonasNaturales(7543913, 'Cordelia Morant', 'cmorant89@wikispaces.com');

--ADICIONAR EMPRESAS.
EXECUTE PC_Proveedores.AD_Empresas(7783953 ,7543913, 'Lazzy');

--MODIFICAR PROVEDORES .
EXECUTE PC_Proveedores.MOD_Proveedores(5855852,3197065840);

--ELIMINAR PROVEEDORES.
EXECUTE PC_Proveedores.EL_Proveedores(5555555);

--CONSULTAR LOS PROVEEDORES DE LA BASE DE DATOS.
SELECT 
PC_Proveedores.CO_Proveedores
FROM DUAL;

/*PC_Compras*/

--ADICIONAR LAS COMPRAS.
EXECUTE PC_Compras.AD_Compras(TO_DATE( '03/29/2016','MM/DD/YYYY'), 7543913);
EXECUTE PC_Compras.AD_Compras(TO_DATE( '08/19/2019','MM/DD/YYYY'), 7783953);
EXECUTE PC_Compras.AD_Compras(TO_DATE( '07/15/2019','MM/DD/YYYY'), 5855852);

--CONSULTAR LA COMPRAS REGISTRADAS EN LA BASE. 
SELECT 
PC_Compras.CO_Compras
FROM DUAL;

/*PC_Insumos*/

--ADICIONAR INSUMOS A LA BASE DE DATOS.
EXECUTE PC_Insumos.AD_Insumos('Cabbage - Red');
EXECUTE PC_Insumos.AD_Insumos('Soup - Campbells Bean Medley');
EXECUTE PC_Insumos.AD_Insumos('Sou88p - Ca8mpbells Bean Medley');

--CONSULTAR LOS INSUMOS REGISTRADOS EN LA BASE DE DATOS.
SELECT 
PC_Insumos.CO_Insumos
FROM DUAL;

--ADICIONAR UNA COMPRA LA CUAL TENIA CIERTO INSUMO.
EXECUTE PC_Insumos.AD_CantidadInsumo('CA-1',1,TO_DATE('11/29/2018','MM/DD/YYYY'),296, 3643460);

--CONSULTAR LAS COMPRAS QUE CONTIENEN INSUMOS.
SELECT
PC_Insumos.CO_CantidadInsumo
FROM DUAL;

/*PC_Productos*/

--ADICIONAR PRODUCTOS A LA BASE DE DATOS.
EXECUTE PC_Productos.AD_Productos('Gaseosa Cocacola');
EXECUTE PC_Productos.AD_Productos('Gaseosa Sprite');

--MOSTRAR LOS PRODUCTOS REGISTRADOS EN LA BASE DE DATOS.
SELECT 
PC_Productos.CO_Productos
FROM DUAL;




/*PC_Zonas*/
--INSERTAR UNA ZONA 
EXECUTE PC_Zonas.AD_Zonas('Citroncirus','O');



/*PC_Empleados*/
--INSERTAR IN EMPLEADO
EXECUTE PC_Empleados.AD_Empleado(9548859, 'Allianora Corkett',  3085711707, NULL);


--INSERTAR EL ACCESO QUE TIENE UN EMPLEADO A UNA ZONA EN UN DETERMINADO TIEMPO.
EXECUTE PC_Empleados.AD_Empleado_Acce(9548859, 1, TO_DATE('09/19/2015','MM/DD/YYYY'),NULL);

--CONSULTAR LOS EMPLEADOS QUE TIENEN ACCESP A UNA ZONA EN UN DETERMINADO TIEMPO.
SELECT 
PC_Empleados.CO_AccesoTiempo
FROM DUAL;

--MODIFICAR EL ACCESO QUE TIENE UN EMPLEADO A UNA ZONA.
EXECUTE PC_Empleados.MOD_Empleado_Acce(9548859, 1, TO_DATE('09/19/2019','MM/DD/YYYY'));

--ELIMINAR UN EMPLEADO
EXECUTE PC_Empleados.EL_Empleado(9548859);

