DROP TABLE Proveedores 
CASCADE CONSTRAINTS  ;

DROP TABLE Empresas 
CASCADE CONSTRAINTS  ;

DROP TABLE PersonasNaturales 
CASCADE CONSTRAINTS  ;

DROP TABLE Compras 
CASCADE CONSTRAINTS  ;

DROP TABLE Insumos 
CASCADE CONSTRAINTS  ;

DROP TABLE CantidadInsumo 
CASCADE CONSTRAINTS  ;

DROP TABLE Productos 
CASCADE CONSTRAINTS  ;

DROP TABLE CantidadProducto 
CASCADE CONSTRAINTS  ;

DROP TABLE Zonas 
CASCADE CONSTRAINTS  ;

DROP TABLE Sectores 
CASCADE CONSTRAINTS  ;

DROP TABLE Mesas 
CASCADE CONSTRAINTS  ;

DROP TABLE Pedidos 
CASCADE CONSTRAINTS  ;

DROP TABLE EstaEn 
CASCADE CONSTRAINTS  ;

DROP TABLE Empleados 
CASCADE CONSTRAINTS  ;

DROP TABLE AccesoTiempo 
CASCADE CONSTRAINTS  ;

DROP TABLE FechaLaboral 
CASCADE CONSTRAINTS  ;

DROP TABLE Labores 
CASCADE CONSTRAINTS  ;

DROP TABLE Despachos 
CASCADE CONSTRAINTS  ;

DROP TABLE sobreUna 
CASCADE CONSTRAINTS  ;

